name: Publish NuGet Package to GitHub Packages

on:
  push:
    tags:
      - 'v*' # タグプッシュ時に実行（例：v1.0.0）

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: dotnet pack --configuration Release --no-build --output ./packages

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push ./packages/NumericalOptimization.*.nupkg \
            --source https://nuget.pkg.github.com/KentaKatayama999/index.json \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --skip-duplicate
